name: ros_utilities CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container:
      image: ghcr.io/bdaiinstitute/ros_utilties_jammy_humble:main
    steps:
    - uses: actions/checkout@v3
    - name: Build and run tests
      run: |
        source /opt/ros/humble/setup.bash
        colcon build --symlink-install
        source install/setup.bash
        colcon test --event-handlers console_direct+
        colcon test-result --all --verbose
