name: ros_utilities CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_jammy_humble:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container:
      image: ghcr.io/bdaiinstitute/spot_ros2_jammy_humble:main
    steps:
    - uses: actions/checkout@v3
    - name: Build and run tests
      run: |
        source /opt/ros/humble/setup.bash
        colcon build --symlink-install
        colcon test
